source 'https://rubygems.org'

gem 'chatx', path: '~/SE/ChatX' #, git: 'https://gitlab.com/izwick-schachter/chatx', branch: 'master'
gem 'se-realtime', git: 'https://github.com/izwick-schachter/se-realtime', branch: 'master'
gem 'se-api', git: 'https://github.com/izwick-schachter/se-api', branch: 'master'
gem 'websocket-driver'
gem 'faye-websocket'
gem 'puma'
gem 'sinatra-activerecord'
gem 'sqlite3'
gem 'rake'
